import '@radix-ui/themes/styles.css';
import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from '@/app/components/layout/navbar'
import { Theme } from '@radix-ui/themes';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Theme>
          <Navbar/>
          <main className={'max-w-screen-lg my-0 mx-auto'}>{children}</main>
      </Theme>
      </body>
    </html>
  );
}
